version: "3"
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      realtimenetwork
  celery:
    build:
      context: ./celery
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      realtimenetwork      
  flower:
    image: mher/flower:0.9.4
    ports:
      - '5555:5555'
    depends_on:
      - redis
      - celery
    environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - FLOWER_PORT=5555
    - FLOWER_BASIC_AUTH=root:tBvsAHF7ZsVPPrYc
    networks:
      realtimenetwork    
  api:
    build:
      context: ./realtimeAPI
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - celery
      - flower
    volumes:
      - ./realtimeAPI:/var/www
    working_dir: /var/www
    restart: always
    command: /bin/sh -c "npm install && npm run start"
    networks:
      realtimenetwork    
networks:
  realtimenetwork:
    external: true
